import {
  IntakeFormData,
  QuestionMetadata,
  ProductRowKey,
  ProcedureRowKey,
} from "@/types/intake";

export const PRODUCT_KEYS: ProductRowKey[] = [
  "OTC/Medicated Shampoos",
  "Hair Oils/Serums",
  "Topical Minoxidil",
  "Oral Minoxidil",
  "Supplements",
];

export const PROCEDURE_KEYS: ProcedureRowKey[] = [
  "PRP/GFC/iPRF",
  "Stem Cells/Exosomes",
  "Hair Transplant",
  "Other",
];

export const INITIAL_FORM_DATA: IntakeFormData = {
  patient_name: "",
  patient_sex: null,
  patient_age: null,

  age_hair_loss_began: null,
  duration: null,
  family_history: [],
  pattern: [],

  diagnosed_conditions: [],
  menstrual_cycle: null,
  pregnancy_related: null,
  adult_acne_oily_skin: null,
  excess_body_facial_hair: null,

  past_6_months: [],
  habits: {
    smoking: null,
    smoking_severity: null,
    alcohol: null,
    hard_water: null,
    hair_wash_frequency: null,
    heating_tools_styling_chemicals: null,
    salon_treatments: null,
    salon_treatment_detail: null,
  },

  products: {
    "OTC/Medicated Shampoos": { used: false, duration: null, helped: null, side_effects: null },
    "Hair Oils/Serums": { used: false, duration: null, helped: null, side_effects: null },
    "Topical Minoxidil": { used: false, duration: null, helped: null, side_effects: null },
    "Oral Minoxidil": { used: false, duration: null, helped: null, side_effects: null },
    "Supplements": { used: false, duration: null, helped: null, side_effects: null },
  },

  procedures: {
    "PRP/GFC/iPRF": { done: false, sessions: null, helped: null },
    "Stem Cells/Exosomes": { done: false, sessions: null, helped: null },
    "Hair Transplant": { done: false, sessions: null, helped: null },
    "Other": { done: false, sessions: null, helped: null },
  },

  past_treatment_side_effects: null,
  past_treatment_side_effects_detail: null,

  sample_type: null,
  consent: null,
};

export const QUESTIONS_METADATA: QuestionMetadata[] = [
  {
    n: 1,
    sectionId: "A",
    sectionTitle: "Personal & Family History",
    key: "age_hair_loss_began",
    title: "At what age did you first notice hair loss?",
    description: "Your approximate age when thinning or shedding first started.",
    hintPrompt: "How old were you when you first noticed your hair falling or thinning?",
    hinglishExample: "e.g., 'Jab main 28 saal ka tha tab shuru hua'",
  },
  {
    n: 2,
    sectionId: "A",
    sectionTitle: "Personal & Family History",
    key: "duration",
    title: "How long has this current hair loss been going on?",
    description: "Select the duration of your active hair shedding or thinning.",
    hintPrompt: "How long has this active hair fall been going on?",
    hinglishExample: "e.g., 'Pichle 8 mahine se' or 'Do saal se zyada ho gaye'",
  },
  {
    n: 3,
    sectionId: "A",
    sectionTitle: "Personal & Family History",
    key: "family_history",
    title: "Does hair loss run in your immediate family?",
    description: "Tap all that apply in your direct family.",
    hintPrompt: "Did anyone in your family—like your father, mother, or siblings—have hair thinning or baldness?",
    hinglishExample: "e.g., 'Mere papa aur bhai dono ke baal kam hain'",
  },
  {
    n: 4,
    sectionId: "A",
    sectionTitle: "Personal & Family History",
    key: "pattern",
    title: "What pattern of hair loss are you experiencing?",
    description: "You can select multiple patterns if you observe more than one.",
    hintPrompt: "Where are you noticing the hair loss? Like at the forehead hairline, the crown at the top, or sudden shedding all over?",
    hinglishExample: "e.g., 'Aage se hairline peeche ja rahi hai aur upar crown pe patle ho rahe hain'",
  },
  {
    n: 5,
    sectionId: "B",
    sectionTitle: "Hormonal & Health Influences",
    key: "diagnosed_conditions",
    title: "Have you been diagnosed with any of these conditions?",
    description: "Underlying health conditions strongly influence hair follicle biology.",
    hintPrompt: "Do you have any medical conditions like thyroid, diabetes, PCOS, or anemia?",
    hinglishExample: "e.g., 'Mujhe hypothyroidism hai' or 'None of these'",
  },
  {
    n: 6,
    sectionId: "B",
    sectionTitle: "Hormonal & Health Influences",
    key: "menstrual_cycle",
    title: "How would you describe your menstrual cycle?",
    description: "Hormonal shifts regulate the hair growth cycle.",
    hintPrompt: "Are your menstrual periods regular, irregular, or are you menopausal?",
    hinglishExample: "e.g., 'Periods are regular' or 'Irregular due to PCOD'",
    femaleOnly: true,
  },
  {
    n: 7,
    sectionId: "B",
    sectionTitle: "Hormonal & Health Influences",
    key: "pregnancy_related",
    title: "Is your hair loss related to pregnancy or childbirth?",
    description: "Postpartum telogen effluvium is very common within 1 year of delivery.",
    hintPrompt: "Are you currently pregnant, or delivered a baby in the past year?",
    hinglishExample: "e.g., 'Delivered 6 months ago' or 'Not applicable'",
    femaleOnly: true,
  },
  {
    n: 8,
    sectionId: "B",
    sectionTitle: "Hormonal & Health Influences",
    key: "adult_acne_oily_skin",
    title: "Do you experience persistent acne or oily facial skin in adulthood?",
    description: "Indicates androgen receptor sensitivity in skin and scalp.",
    hintPrompt: "Do you frequently get pimples, cystic acne, or very oily skin on your face?",
    hinglishExample: "e.g., 'Haan, face bohot oily rehta hai aur acne hoti hai'",
  },
  {
    n: 9,
    sectionId: "B",
    sectionTitle: "Hormonal & Health Influences",
    key: "excess_body_facial_hair",
    title: "Have you noticed excess body or facial hair growth (hirsutism)?",
    description: "Coarse hair on chin, upper lip, chest, or abdomen.",
    hintPrompt: "Have you noticed any unusual coarse hair growth on your chin, jawline, or body?",
    hinglishExample: "e.g., 'Thodi facial hair growth hai chin pe'",
  },
  {
    n: 10,
    sectionId: "C",
    sectionTitle: "Lifestyle & Environmental Triggers",
    key: "past_6_months",
    title: "In the past 6 months, did you experience any of these events?",
    description: "Systemic stressors trigger acute telogen effluvium 2–3 months later.",
    hintPrompt: "In the last 6 months, did you have high fever like dengue or COVID, major stress, surgery, or sudden weight loss?",
    hinglishExample: "e.g., '4 mahine pehle severe dengue fever hua tha'",
  },
  {
    n: 11,
    sectionId: "C",
    sectionTitle: "Lifestyle & Environmental Triggers",
    key: "habits",
    title: "Daily habits & scalp environment",
    description: "Quickly review habits affecting hair vitality and mineral buildup.",
    hintPrompt: "Do you smoke or drink? Do you have hard water where you wash your hair, and how often do you shampoo?",
    hinglishExample: "e.g., 'Hard water supply hai, alternate days wash karta hoon, smoking 4-5 a day'",
  },
  {
    n: 12,
    sectionId: "D",
    sectionTitle: "Current Hair Care & Treatments",
    key: "products",
    title: "Which hair products or medications have you tried?",
    description: "Tap any product you have used to note duration, response, and side effects.",
    hintPrompt: "Have you used Minoxidil, hair serums, medicated shampoos, or supplements like biotin?",
    hinglishExample: "e.g., 'Topical minoxidil 5% use kiya tha 4 mahine, accha result tha'",
  },
  {
    n: 13,
    sectionId: "D",
    sectionTitle: "Current Hair Care & Treatments",
    key: "procedures",
    title: "Have you undergone any in-clinic procedures?",
    description: "PRP, GFC, stem cells/exosomes, or hair transplant history.",
    hintPrompt: "Have you ever had PRP sessions, GFC, or a hair transplant done?",
    hinglishExample: "e.g., 'Haan, pichle saal 3 PRP sessions karwaye the'",
  },
  {
    n: 14,
    sectionId: "D",
    sectionTitle: "Current Hair Care & Treatments",
    key: "past_treatment_side_effects",
    title: "Did you have any side effects or poor reactions to past treatments?",
    description: "Important for doctors to avoid re-triggering scalp irritation, headaches, or allergies.",
    hintPrompt: "Did you ever have a bad reaction or side effect from any hair lotion, pill, or clinic treatment?",
    hinglishExample: "e.g., 'Minoxidil se scalp pe itching aur flaking hone lagi thi'",
  },
  {
    n: 15,
    sectionId: "E",
    sectionTitle: "Sample Collection & Consent",
    key: "sample_type",
    title: "Preferred sample type for root & genetic testing",
    description: "For follicular DNA and micronutrient analysis.",
    hintPrompt: "For your follicle and genetic test, do you prefer a saliva swab, a blood test, or either?",
    hinglishExample: "e.g., 'Saliva swab is easier for me' or 'Either is fine'",
  },
  {
    n: 16,
    sectionId: "E",
    sectionTitle: "Sample Collection & Consent",
    key: "consent",
    title: "Consent to sample collection and genetic hair analysis",
    description: "Your data is strictly confidential and used solely for personalized trichology treatment.",
    hintPrompt: "Do you consent to sample collection and genetic analysis for your hair treatment plan?",
    hinglishExample: "e.g., 'Yes, I agree' or 'Haan, consent hai'",
  },
];

/**
 * Realistic clinical test personas for reviewers to test with 1-click
 */
export const DEMO_PERSONAS = [
  {
    id: "persona-ramesh",
    name: "Ramesh Sharma (52M, Hereditary Androgenetic Alopecia)",
    description: "Male with 3-year crown thinning, father had baldness, hard water wash.",
    data: {
      patient_name: "Ramesh Sharma",
      patient_sex: "male" as const,
      patient_age: 52,
      age_hair_loss_began: 48,
      duration: "Over a year" as const,
      family_history: ["Father had hair loss" as const, "Siblings with thinning or baldness" as const],
      pattern: ["Receding hairline" as const, "Thinning at crown" as const],
      diagnosed_conditions: ["Diabetes" as const],
      menstrual_cycle: "Not applicable" as const,
      pregnancy_related: "Not applicable" as const,
      adult_acne_oily_skin: "no" as const,
      excess_body_facial_hair: "no" as const,
      past_6_months: ["High stress or emotional trauma" as const],
      habits: {
        smoking: "yes" as const,
        smoking_severity: "Mild <5/day" as const,
        alcohol: "yes" as const,
        hard_water: "yes" as const,
        hair_wash_frequency: "Alternate Days" as const,
        heating_tools_styling_chemicals: "no" as const,
        salon_treatments: "no" as const,
        salon_treatment_detail: null,
      },
      products: {
        "OTC/Medicated Shampoos": { used: true, duration: ">6mo" as const, helped: "yes" as const, side_effects: "no" as const },
        "Hair Oils/Serums": { used: true, duration: ">6mo" as const, helped: "no" as const, side_effects: "no" as const },
        "Topical Minoxidil": { used: true, duration: "3-6mo" as const, helped: "yes" as const, side_effects: "no" as const },
        "Oral Minoxidil": { used: false, duration: null, helped: null, side_effects: null },
        "Supplements": { used: true, duration: "3-6mo" as const, helped: "yes" as const, side_effects: "no" as const },
      },
      procedures: {
        "PRP/GFC/iPRF": { done: true, sessions: "1-3" as const, helped: "yes" as const },
        "Stem Cells/Exosomes": { done: false, sessions: null, helped: null },
        "Hair Transplant": { done: false, sessions: null, helped: null },
        "Other": { done: false, sessions: null, helped: null },
      },
      past_treatment_side_effects: "no" as const,
      past_treatment_side_effects_detail: null,
      sample_type: "Saliva" as const,
      consent: "yes" as const,
    },
  },
  {
    id: "persona-priya",
    name: "Priya Menon (27F, Post-Dengue Telogen + PCOS)",
    description: "Female with acute sudden shedding after dengue 4 months ago & PCOS.",
    data: {
      patient_name: "Priya Menon",
      patient_sex: "female" as const,
      patient_age: 27,
      age_hair_loss_began: 26,
      duration: "Less than 6 months" as const,
      family_history: ["Mother had hair loss" as const],
      pattern: ["Widening part line" as const, "Sudden excessive shedding" as const],
      diagnosed_conditions: ["PCOS/PCOD" as const, "Anemia" as const],
      menstrual_cycle: "Irregular" as const,
      pregnancy_related: "Not applicable" as const,
      adult_acne_oily_skin: "yes" as const,
      excess_body_facial_hair: "yes" as const,
      past_6_months: ["Fever with illness (COVID, Dengue, Typhoid)" as const, "Crash dieting or major weight loss" as const],
      habits: {
        smoking: "no" as const,
        smoking_severity: null,
        alcohol: "no" as const,
        hard_water: "yes" as const,
        hair_wash_frequency: "Weekly" as const,
        heating_tools_styling_chemicals: "yes" as const,
        salon_treatments: "yes" as const,
        salon_treatment_detail: "Keratin treatment done 8 months ago",
      },
      products: {
        "OTC/Medicated Shampoos": { used: true, duration: "<3mo" as const, helped: "no" as const, side_effects: "no" as const },
        "Hair Oils/Serums": { used: true, duration: "3-6mo" as const, helped: "no" as const, side_effects: "no" as const },
        "Topical Minoxidil": { used: false, duration: null, helped: null, side_effects: null },
        "Oral Minoxidil": { used: false, duration: null, helped: null, side_effects: null },
        "Supplements": { used: true, duration: "<3mo" as const, helped: "no" as const, side_effects: "no" as const },
      },
      procedures: {
        "PRP/GFC/iPRF": { done: false, sessions: null, helped: null },
        "Stem Cells/Exosomes": { done: false, sessions: null, helped: null },
        "Hair Transplant": { done: false, sessions: null, helped: null },
        "Other": { done: false, sessions: null, helped: null },
      },
      past_treatment_side_effects: "no" as const,
      past_treatment_side_effects_detail: null,
      sample_type: "Blood" as const,
      consent: "yes" as const,
    },
  },
];
